# Generated by Django 2.1.3 on 2019-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ocupation',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
